### ISSUE TITLE
gmap function don't work

### ISSUE THREAD

**Issue by vectoranalytica** [rspatial/dismo#1]
The gmap function must be updated to download maps

1. the base url must be changed to: https://maps.googleapis.com/maps/api/staticmap?

2. the google API_KEy must be added to gurl <- paste(gurl, "center=", ctr, "&zoom=", zoom, "&size=", s, "&maptype=", type,"&key=", key,"&format=gif&sensor=false&scale=", scale, sep = "")

**Comment by millicentFalls** [comment]
Dear vectoranalytica

can you please give some additional information about how to add in addition url information. For example, if I use this script :
g= gmap('Sydney, Australia', type = 'satellite')
I get an error code
How do I write the information you have given above into my line of code?

**Comment by rhijmans** [comment]
That has been updated, but I will remove this from dismo because (a) the need for a Google user name and (b) there are now many other packages that provide this service. For example: https://cran.r-project.org/web/packages/maptiles/index.html
