### ISSUE TITLE
Can't install dismo dependencies

### ISSUE THREAD

**Issue by davidedelvento** [rspatial/dismo#12]
This happens on Ubuntu 16.04 (ok, almost EOL, but not there yet), and 18.04 with R versions v3.2.3, and v3.4.4 respectively. With Ubuntu and 20.04 and R v3.6.3 the error is different, but it still does not install.

Am I doing something wrong or do the dismo dependencies have an issue? FWIW it fails in the same way also with either `dependencies=FALSE` or without that argument on the older OSes, but installation succeeds with `dependencies=FALSE` on Ubuntu 20.04

```
$ sudo Rscript --slave --no-save --no-restore-history -e "install.packages(pkgs='dismo', dependencies=TRUE, repos=c('http://ftp.heanet.ie/mirrors/cran.r-project.org/'));"

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
Warning: dependencies ‘raster’, ‘terra’, ‘rgdal’, ‘rgeos’, ‘ROCR’, ‘deldir’ are not available
trying URL 'http://ftp.heanet.ie/mirrors/cran.r-project.org/src/contrib/dismo_1.3-3.tar.gz'
Content type 'application/x-gzip' length 1811212 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

ERROR: dependency ‘raster’ is not available for package ‘dismo’
* removing ‘/usr/local/lib/R/site-library/dismo’

The downloaded source packages are in
‘/tmp/Rtmp4ar6Jc/downloaded_packages’
Warning message:
In install.packages(pkgs = "dismo", dependencies = TRUE, repos = c("http://ftp.heanet.ie/mirrors/cran.r-project.org/")) :
  installation of package ‘dismo’ had non-zero exit status
```

**Comment by rhijmans** [comment]
I have lowered the R requirement for raster to version 3.4 ---- on github: https://github.com/rspatial/raster
Does that help?

**Comment by davidedelvento** [comment]
That seemed to have fixed the problem. Thanks!
