### ISSUE TITLE
Suppress massage when running maxent()

### ISSUE THREAD

**Issue by sgvignali** [rspatial/dismo#17]
The message **"This is MaxEnt version x.x.x"** is printed every time a model is trained, even when using `silent = TRUE`. 
When several models are trained in a for loop this is a bit annoying and it would be nice to be able to silence them.

I think you just need to pass the argument `silent` to the `maxent()` function on line 297:
https://github.com/rspatial/dismo/blob/master/R/maxent.R#L294-L297

**Comment by rhijmans** [comment]
Thanks, that message is now always suppressed; unless you run `maxent()`
