### ISSUE TITLE
RandomPoints output

### ISSUE THREAD

**Issue by elgabbas** [rspatial/dismo#19]
Hello,

I am using `RandomPoints` function to generate random points using a probability weight. Below, I compare the results using dismo vs raptr packages.

```
require(raster)
RR <- raster()
RR <- disaggregate(RR, 10)
RR[] <- 1:ncell(RR)/ncell(RR)
RandomDismo <- dismo::randomPoints(mask = RR, n = 10000, prob = TRUE)
RandomRaptr <- raptr::randomPoints(mask = RR, n = 10000, prob = TRUE)
plot(RR, box = F, axes = F, legend = F)
points(RandomDismo, pch = 19, cex = 0.25, col = "blue")
```
![image](https://user-images.githubusercontent.com/7375051/125337822-bb589b80-e34f-11eb-80cf-1d4003e70550.png)
```
plot(RR, box = F, axes = F, legend = F)
points(RandomRaptr, pch = 19, cex = 0.25, col = "blue")
```
![image](https://user-images.githubusercontent.com/7375051/125337880-ce6b6b80-e34f-11eb-9ea7-f3d280058c3e.png)

I expect more points to be sampled from green areas (higher values at the mask grid). 
I understand that both functions should not be identical due to randomizations, but the pattern for dismo points is not convincing. I quote this from the help `dismo::randomPoints` function:
> `If the coordinate reference system (of mask) is longitude/latitude, sampling is weighted by the size of the cells. That is, because cells close to the equator are larger than cells closer to the poles, equatorial cells have a higher probability of being selected.`

This may be the reason for the example provided above, but I noticed the same issue when using a mask layer in an equal area projection. 

The intention of using the function was to produce spatially biased background locations to be used in a maxent model. The area of interest was the Nordic Sea (Arctic Ocean) with the mask layer projected in an equal-area projection.

Cheers,
Ahmed

**Comment by rhijmans** [comment]
Thanks for reporting this. When weights were used, lonlat correction was always applied, and given too much weight relative to the other weights. Things look better now, I think

```
library(dismo)
r <- raster(resolution=2)
values(r) <- 1:ncell(r)/ncell(r)

plottab <- function(x) {
	d <- as.data.frame(table(x[,2]))
	d[,1] <- as.numeric(as.character(d[,1]))
	plot(d)
}

pd1 <- dismo::randomPoints(r, n = 1000, prob = TRUE, lonlatCorrection=T)

pd2 <- dismo::randomPoints(r, n = 1000, prob =F, lonlatCorrection=T)

pd3 <- dismo::randomPoints(r, n = 1000, prob = T, lonlatCorrection=F)

crs(r) <- "+proj=utm +zone=1"
pd4 <- dismo::randomPoints(r, n = 1000, prob = TRUE, lonlatCorrection=F)

par(mfrow=c(2,2), mar=c(2,2,1,1))
plottab(pd1)
plottab(pd2)
plottab(pd3)
plottab(pd4)

```

**Comment by elgabbas** [comment]
Worked as expected now. Thanks
