### ISSUE TITLE
cv.threshold definition

### ISSUE THREAD

**Issue by ctlamb** [rspatial/dismo#2]
Hello, I am using GBM and Dismo to created boosted regression trees for species distribution modelling, I then predict these models onto raster stacks, and classify this continuous raster into presence/absence using a threshold.

I have been trying to find a definition of cv.threshold (MODEL$cv.statistics$cv.threshold), as I think that is what I want to use as my threshold. But can't seem to find any definitions. Aside from mention in this [paper](https://onlinelibrary.wiley.com/doi/pdf/10.1002/ece3.3847)

Thanks

**Comment by rhijmans** [comment]
I am sorry, I can't help you with that.
