### ISSUE TITLE
 java.awt.HeadlessException error running maxent through rJava

### ISSUE THREAD

**Issue by ggbee44** [rspatial/dismo#21]
I don't know if this is the right place to put this question but I am trying to run the maxent function in the dismo package on macOS through rJava and keep getting this error message.

`Error in rJava::.jcall(mxe, "S", "fit", c("autorun", "-e", afn, "-o", : java.awt.HeadlessException`

Has anyone seen it before and know how to fix it? Thank you so much!

**Comment by rhijmans** [comment]
It is a fair place to ask the question. I have no idea though, beyond what google can tell you.
