### ISSUE TITLE
problems loading raster package

### ISSUE THREAD

**Issue by randle-cp** [rspatial/dismo#24]
Thank you in advance.  I work with students doing SDM and we rely on dismo for most of our modeling. Recently, when trying to load the library, two students got an error message- 'error package 'raster' could not be loaded'.  Both students had recently loaded the newest version of R and RStudio and are looking to run SDM for the first time. Dismo loads fine on my computer, though I haven't updated R or Rstudio in a few months.  Any help would be welcome.

**Comment by rhijmans** [comment]
This is because of a temporary glitch at CRAN with the `terra` package (on which `raster` depends.. The best (and simple) work-around is to is install the development version of `terra`, and then install raster and dismo again; like this:

```
install.packages('terra', repos='https://rspatial.r-universe.dev')
install.packages("raster")
install.packages("dismo")
```

**Comment by randle-cp** [comment]
Thank you so much.  And while I’m thanking you, we love the rspatial.org site.  It’s been an amazing tool.

**Comment by rhijmans** [comment]
That is great to hear. Thank you.
