### ISSUE TITLE
Convex Hull not working properly in version 1.3-5

### ISSUE THREAD

**Issue by jivelasquezt** [rspatial/dismo#28]
ConvHull returns the correct convex hull polygon for example data in version 1.1-4. 

```
pts <- matrix(c(17, 42, 85, 70, 19, 53, 26, 84, 84, 46, 48, 85, 4, 95, 48, 54, 66, 
 74, 50, 48, 28, 73, 38, 56, 43, 29, 63, 22, 46, 45, 7, 60, 46, 34, 14, 51, 70, 31, 39, 26), ncol=2)
train <- pts[1:12, ]
ch <- convHull(train)
plot(ch)
```
<img width="423" alt="image" src="https://user-images.githubusercontent.com/3853701/170784907-63dff19d-b55c-4512-b6a8-a5a0e473b237.png">

In version 1.3-5 running the same code returns this: 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/3853701/170784571-a8029459-05bb-4917-85a5-fa2e2f831f9b.png">

**Comment by rhijmans** [comment]
Thanks for reporting this. I am sorry it took me so long but it is fixed now.
