### ISSUE TITLE
Rug plot missing from first variable from gbm.plot()

### ISSUE THREAD

**Issue by eogoodwin** [rspatial/dismo#3]
If you're plotting all variables, then variable.no=0.  The test for plotting the rug therefore fails, because the zeroth column is not a vector.  In this test 'variable.no' should be replaced with 'k' I think.  Or, the very first test there could be 'if (plot.count==1 & n.plots==1)'.

if (plot.count == 1) {
			if (write.title) {
				title(paste(response.name," - page ",n.pages,sep=""))
			}
			if (rug & is.vector(data[,gbm.call$gbm.x[variable.no]])) {
				rug(quantile(data[,gbm.call$gbm.x[variable.no]], probs = seq(0, 1, 0.1), na.rm = TRUE))
			}

**Comment by dgregory897** [comment]
Hi there, 
I’m trying to attain the rug plots of my gbm models but every time I try I keep getting the error : 
Incorrect number of dimensions for gbm.call

Any ideas why that would happen - the BRTs all ran fine but gbm.plot seems to think there is something wrong with the models structure?

**Comment by rhijmans** [comment]
Thank you, I have implemented that. Sorry for the long delay
