### ISSUE TITLE
R stops working when I try to run maxent()

### ISSUE THREAD

**Issue by EduardoArle** [rspatial/dismo#32]
Dear Prof. Hijmans,

I am having trouble since yesterday, and I am hoping you could give me some light!

I am using macOS Monterey version 12.2.1 ; R version 4.2.2. 

Everything was working fine, and suddenly my R sessions started getting stuck forever. After chasing the bugs for quite a long time, I found out that every function that used plot involving characters was making it get stuck. I partially fixed the problem by including this line in the beginning of my code: "options(bitmapType='cairo')" . 

However, dismo::maxent is still causing the problem to happen. It is not an issue with the data, because it problem also happens when I try to run the example provided by dismo. 

Because of the issue with the plotting I found before, I suppose there is something going wrong with the plotting of the variable contribution, and causing R to be stuck. I tried to crack into the function and run line by line to understand exactly where the bug is, but I did not manage to figure it out. 

Sorry for bothering with this long question. I have been cracking my head for more than 12 hours straight, and I wonder if you have come across similar issues.

Thank you very much,
Eduardo

**Comment by rhijmans** [comment]
I have never encountered this. I would seem that something has gone wrong with your R installation. I would start by removing it and then installing it again.

**Comment by EduardoArle** [comment]
I managed to solve the problem! Thank you very much!
