### ISSUE TITLE
install Error 

### ISSUE THREAD

**Issue by meteorolog90** [rspatial/dismo#33]
```
install.packages("https://cran.r-project.org/src/contrib/Archive/dismo/dismo_1.3-3.tar.gz",repos=NULL,type="source")
Installing package into '/users/oks001/bin/R-oks/renv/library/R-3.6/x86_64-redhat-linux-gnu'
(as 'lib' is unspecified)
trying URL 'https://cran.r-project.org/src/contrib/Archive/dismo/dismo_1.3-3.tar.gz'
Content type 'application/x-gzip' length 1811212 bytes (1.7 MB)
==================================================
downloaded 1.7 MB

```
* installing *source* package 'dismo' ...
** package 'dismo' successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/users/oks001/bin/R-oks/renv/library/R-3.6/x86_64-redhat-linux-gnu/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I"/users/oks001/bin/R-oks/renv/library/R-3.6/x86_64-redhat-linux-gnu/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c percRank.cpp -o percRank.o
g++ -m64 -std=gnu++11 -shared -L/usr/lib64/R/lib -Wl,-z,relro -o dismo.so RcppExports.o percRank.o -L/usr/lib64/R/lib -lR
installing to /users/oks001/bin/R-oks/renv/library/R-3.6/x86_64-redhat-linux-gnu/00LOCK-dismo/00new/dismo/libs
** R
** data
** inst
** byte-compile and prepare package for lazy loading
Error in setMethod("convHull", signature(p = "matrix"), function(p, n = 1,  :
  no existing definition for function 'convHull'
Error: unable to load R code in package 'dismo'
Execution halted
ERROR: lazy loading failed for package 'dismo'
* removing '/users/oks001/bin/R-oks/renv/library/R-3.6/x86_64-redhat-linux-gnu/dismo'
Warning message:
In utils::install.packages("https://cran.r-project.org/src/contrib/Archive/dismo/dismo_1.3-3.tar.gz",  :
  installation of package '/tmp/RtmpBgCGVf/downloaded_packages/dismo_1.3-3.tar.gz' had non-zero exit status

**Comment by rhijmans** [comment]
I see the same.  I suspect you would also need an older version of raster (and perhaps terra) for to install this. But I am not going to look into it.
