### ISSUE TITLE
minor typo in xlab of plot function

### ISSUE THREAD

**Issue by EGarciaBerthou** [rspatial/dismo#34]
In the corresponding plot function in dismo and also
https://rspatial.org/raster/sdm/5_sdm_models.html
https://rspatial.org/sdm/5_sdm_models.html#model-fitting

you should replace "false positve rate" with "false positive rate"

![image](https://user-images.githubusercontent.com/51483439/215461275-ed45d08e-101a-4f10-9b05-3098a5449812.png)

Thanks a lot for the dismo package and such useful internet resources and publications!

**Comment by rhijmans** [comment]
Thank you, fixed now.
