### ISSUE TITLE
CRAN push?

### ISSUE THREAD

**Issue by SimonDedman** [rspatial/dismo#40]
Hi folks,

Would you have any aversion to pushing the latest version of dismo to CRAN at some point when it's convenient?

I'm sorry to even ask - the reason is, I'm having to push recent edits of my package to CRAN in order to address previous dependencies on rgdal etc, but doing so will render the package unable to be installed, since it relies on dismo v1.3-10, which isn't on CRAN, but includes [the tweaks you very kindly made a couple of months ago](https://github.com/rspatial/dismo/issues/37).

Many thanks in advance. Best wishes,

Simon

**Comment by rhijmans** [comment]
It is on CRAN now.
