### ISSUE TITLE
Prediction with maxent no longer available?

### ISSUE THREAD

**Issue by gepinillab** [rspatial/dismo#51]
Dear Robert,

https://github.com/rspatial/dismo/blob/30385aeeca307f676f8bf6ff36001a0529fd583b/R/maxent.predict.R#L38

The last update of the dismo package on CRAN (1.3-16) breaks the option to predict maxent objects even with RasterStacks (not just spatRasters). Is this the expected behavior?

Best,
Gonzalo

**Comment by rhijmans** [comment]
What makes you say that? See, for example, the example in `?dismo::maxent`.

**Comment by gepinillab** [comment]
Apologies for the false issue. I did not check the code correctly and had internal issues when transforming to rasterStacks.

Thanks for the quick reply.
